spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://127.0.0.1:5432/ordersdb
    username: orders
    password: orders
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      #ddl-auto: create
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
      
server:
  port: 8085 